# Site settings
title: Perrine Gogneaux
header-img: img/home-bg.jpg
email: perrine.gogneaux@gmail.com
copyright_name: Perrine Gogneaux
description: "Écrire sur mes envies"
baseurl: ""
url: "http://localhost:4000"
twitter_username: PerrineGogneaux
instagram_username: PerrineGogneaux
# github_username:  davidtmiller
# facebook_username:  IronSummitMedia
email_username:  perrine.gogneaux@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
